# -*- coding: utf-8 -*-
"""tut1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100e7DDb5EvzwikPdM4udlCsFTfdp9hSF
"""

print("Twinkle,Twinkle, little star.")
print("How I wonder what you are!")
print("Up above the world so high,")
print("Like a diamond in the sky.")
print("Twinkle,Twinkle, little star.")
print("How I wonder what you are!")

first_name = input("Enter the first name:")
last_name = input("Enter the last name: ")
print(last_name,first_name)

radius = int(input("Enter the radius : "))
pi = 3.14
area = pi*radius*radius
print(area)

color_list = ["red","green","white","black"]
print(color_list[0])
print(color_list[3])

number = int(input("Enter the number: "))
ones = number
tens = number*10 + ones
hundreds = number*100 + tens
add = ones + tens + hundreds
print(add)

x = str(input("Enter the number: ")).split(",")
print(x)
x = tuple(x)
print(x)

celsius = float(input("Enetr the temperature in celsius: "))
fahrenheit = 1.8*celsius + 32
print(fahrenheit)

first , second = int(input("Enter the first number: ")),int(input("Enter the second number: "))
print (second , first)
y = second + 1 + first + 1
print(y)

num = int(input("Enter the number: "))
if (num%2 == 0) : print("It is an even number.")
else : print("It is an odd number.")

year = int(input("Enter the year: "))
if (year%4 == 0) : print("It is an leap year.")
else : print("It is not an leap year.")

x1,y1 = int(input("x1:")), int(input("y1:"))
x2,y2 = int(input("x2:")), int(input("y2:"))
distance = ((x2 - x1)**2 + (y2 - y1)**2)**0.5
print(distance)

a1, a2, a3 = float(input("a1:")),float(input("a2:")),float(input("a3:"))
sum = a1 + a2 + a3
if (sum == 180) : print("This is a triangle.")
else : print("This is not a triangle.")

principle ,rate ,time = int(input("principle: ")), int(input("rate: ")), int(input("time: "))
CI = principle*((1+rate)**time)
print(CI)

N = int(input("Enter the number : "))
c = 0
for i in range (2,N):
 if(N % i == 0) :
 c = c + 1
if c > 0:
 print("Not Prime")
else:
 print("Prime")

n = int(input("Enter the number: "))
sum = 0
for i in range(1,n+1) :
 sum = sum + i**2

print(sum)